-- mod-version:2 -- lite-xl 2.0
local syntax = require "core.syntax"

syntax.add {
	name = "GD Script",
	files = { "%.gd$" },
	comment = "#",
	patterns = {
		{ pattern = "#.-\n",                  type = "comment"  },
		{ pattern = { "\"\"\"", "%\"\"\"" },  type = "comment"  },
		{ pattern = { '"', '"', '\\' },       type = "string"   },
		{ pattern = { "`", "`", '\\' },       type = "string"   },
		{ pattern = { "'", "'", '\\' },       type = "string"   },
		{ pattern = "0[oO_][0-7]+",           type = "number"   },
		{ pattern = "-?0x[%x_]+",             type = "number"   },
		{ pattern = "-?%d+_%d",               type = "number"   },
		{ pattern = "-?%d+[%d%.eE]*f?",       type = "number"   },
		{ pattern = "-?%.?%d+f?",             type = "number"   },
		{ pattern = "[%+%-=/%*%^%%<>!~|&]",   type = "operator" },
		{ pattern = ":=",                     type = "operator" },
		{ pattern = "[%a_][%w_]*%f[(]",       type = "function" },
		{ pattern = "[%a_][%w_]*",            type = "symbol"   },
		{ pattern = "{%a_}{%w_}*",            type = "symbol"   },
	},
	symbols = {
		["if"]          = "keyword",
		["else"]        = "keyword",
		["elif"]        = "keyword",
		["for"]         = "keyword",
		["while"]       = "keyword",
		["match"]       = "keyword",
		["break"]       = "keyword",
		["continue"]    = "keyword",
		["pass"]        = "keyword",
		["return"]      = "keyword",
		["class"]       = "keyword",
		["extends"]     = "keyword",
		["is"]          = "keyword",
		["as"]          = "keyword",
		["self"]        = "keyword",
		["tool"]        = "keyword",
		["signal"]      = "keyword",
		["func"]        = "keyword",
		["static"]      = "keyword",
		["const"]       = "keyword",
		["enum"]        = "keyword",
		["var"]         = "keyword",
		["onready"]     = "keyword",
		["export"]      = "keyword",
		["setget"]      = "keyword",
		["breakpoint"]  = "keyword",
		["preload"]     = "keyword",
		["yield"]       = "keyword",
		["assert"]      = "keyword",
		["remote"]      = "keyword",
		["master"]      = "keyword",
		["puppet"]      = "keyword",
		["remotesync"]  = "keyword",
		["mastersync"]  = "keyword",
		["puppetsync"]  = "keyword",
		["class_name"]  = "keyword2",
		["TAU"]         = "keyword2",
		["INF"]         = "keyword2",
		["NAN"]         = "keyword2",
		["PI"]          = "keyword2",
	},
}

